# Generated by Django 4.0.2 on 2022-03-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_alter_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.productsize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.user')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
