# Generated by Django 4.0.2 on 2022-03-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_status',
        ),
    ]
