# Generated by Django 4.0.2 on 2022-03-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', through='products.ProductSize', to='products.Size'),
        ),
    ]
