# Generated by Django 4.0.2 on 2022-03-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_informationimage_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discout_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
