# Generated by Django 4.0.2 on 2022-03-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discout_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discout_rate',
            new_name='discount_rate',
        ),
    ]
